In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer

# Load model and tokenizer
model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-3-mini-4k-instruct",
    # device_map="cuda",
    torch_dtype="auto",
    trust_remote_code=False,
)
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")

c:\Users\ptpl-648\Desktop\Hands_on_LLM\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
W0822 15:25:55.982000 25088 Lib\site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
Loading checkpoint shards: 100%|██████████| 2/2 [00:13<00:00,  6.56s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [4]:
prompt = "Write an email apologizing to Sarah for the tragic gardening mishap. Explain how it happened.<|assistant|>"

# Tokenize the input prompt
input_ids = tokenizer(prompt, return_tensors="pt").input_ids

# Generate the text
generation_output = model.generate(
  input_ids=input_ids,
  max_new_tokens=100
)

# Print the output
print(tokenizer.decode(generation_output[0]))

You are not running the flash-attention implementation, expect numerical differences.


Write an email apologizing to Sarah for the tragic gardening mishap. Explain how it happened.<|assistant|> Subject: Sincere Apologies for the Gardening Mishap


Dear Sarah,


I hope this message finds you well. I am writing to express my deepest apologies for the unfortunate incident that occurred in your garden yesterday.


As you know, I have always admired the beauty and tranquility of your garden. It was with great disappointment that I witnessed the accidental damage caused to your prized rose bushes


In [5]:
print(input_ids)

tensor([[14350,   385,  4876, 27746,  5281,   304, 19235,   363,   278, 25305,
           293, 16423,   292,   286,   728,   481, 29889, 12027,  7420,   920,
           372,  9559, 29889, 32001]])


In [6]:
for id in input_ids[0]:
    print(tokenizer.decode(id))

Write
an
email
apolog
izing
to
Sarah
for
the
trag
ic
garden
ing
m
ish
ap
.
Exp
lain
how
it
happened
.
<|assistant|>


In [7]:
generation_output

tensor([[14350,   385,  4876, 27746,  5281,   304, 19235,   363,   278, 25305,
           293, 16423,   292,   286,   728,   481, 29889, 12027,  7420,   920,
           372,  9559, 29889, 32001,  3323,   622, 29901,   317,  3742,   406,
          6225, 11763,   363,   278, 19906,   292,   341,   728,   481,    13,
            13,    13, 29928,   799, 19235, 29892,    13,    13,    13, 29902,
          4966,   445,  2643, 14061,   366,  1532, 29889,   306,   626,  5007,
           304,  4653,   590,  6483,   342,  3095, 11763,   363,   278,   443,
          6477,   403, 15134,   393, 10761,   297,   596, 16423, 22600, 29889,
            13,    13,    13,  2887,   366,  1073, 29892,   306,   505,  2337,
          7336,  2859,   278, 15409,   322, 22024,   339,  1793,   310,   596,
         16423, 29889,   739,   471,   411,  2107, 23451,   358,   393,   306,
         16277,   287,   278, 11423,   284, 18658,  8581,   304,   596,  3691,
         24688, 11492, 27089,   267]])

In [8]:
print(tokenizer.decode(4876))
print(tokenizer.decode(292))
print(tokenizer.decode(8581))

email
ing
caused


# **Comparing LLM Tokenizers**

In [9]:
from transformers import AutoModelForCausalLM, AutoTokenizer

colors_list = [
    '102;194;165', '252;141;98', '141;160;203',
    '231;138;195', '166;216;84', '255;217;47'
]

def show_tokens(sentence, tokenizer_name):
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
    token_ids = tokenizer(sentence).input_ids
    for idx, t in enumerate(token_ids):
        print(
            f'\x1b[0;30;48;2;{colors_list[idx % len(colors_list)]}m' +
            tokenizer.decode(t) +
            '\x1b[0m',
            end=' '
        )

In [10]:
text = """
English and CAPITALIZATION
🎵 鸟
show_tokens False None elif == >= else: two tabs:"    " Three tabs: "       "
12.0*50=600
"""

In [11]:
show_tokens(text, "bert-base-cased")

[CLS] English and CA ##PI ##TA ##L ##I ##Z ##AT ##ION [UNK] [UNK] show _ token ##s F ##als ##e None el ##if = = > = else : two ta ##bs : " " Three ta ##bs : " " 12 . 0 * 50 = 600 [SEP] 

In [12]:
show_tokens(text, "gpt2")


 English  and  CAP ITAL IZ ATION 
 � � �  � � � 
 show _ t ok ens  False  None  el if  ==  >=  else :  two  tabs :"        "  Three  tabs :  "              " 
 12 . 0 * 50 = 600 
 

In [13]:
show_tokens(text, "google/flan-t5-small")

English and CA PI TAL IZ ATION  <unk>  <unk> show _ to ken s Fal s e None  e l if = = > = else : two tab s : " " Three tab s : " " 12. 0 * 50 = 600  </s> 

In [14]:
show_tokens(text, "facebook/galactica-1.3b")


 English  and  CAP ITAL IZATION 
 � � � �  � � � 
 show _ tokens  False  None  elif   ==   > =  else :  two  t abs : "      "  Three  t abs :   "         " 
 1 2 . 0 * 5 0 = 6 0 0 
 

In [15]:
show_tokens(text, "microsoft/Phi-3-mini-4k-instruct")

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


 
 English and C AP IT AL IZ ATION 
 � � � �  � � � 
 show _ to kens False None elif == >= else : two tabs :"    " Three tabs : "       " 
 1 2 . 0 * 5 0 = 6 0 0 
 

# Contextualized Word Embeddings From a Language Model (Like BERT)

In [16]:
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-base")

model = AutoModel.from_pretrained("microsoft/deberta-base")

# Tokenize the sentence
tokens = tokenizer('Hello world', return_tensors='pt')

# Process the tokens
output = model(**tokens)[0]

In [17]:
output.shape

torch.Size([1, 4, 768])

In [19]:
for token in tokens.input_ids[0:2]:
    print(tokenizer.decode(token))

[CLS]Hello world[SEP]


In [20]:
output

tensor([[[ 0.0473, -0.0435, -0.0812,  ...,  0.0121,  0.0395, -0.0462],
         [-1.1017, -0.7390, -0.7409,  ..., -0.4467,  0.3183, -0.4456],
         [ 1.0047,  0.6782, -0.4958,  ...,  0.2436, -0.3662,  0.5453],
         [ 0.2161,  0.0714, -0.1412,  ...,  0.0635,  0.1943,  0.0773]]],
       grad_fn=<AddBackward0>)

# Text Embeddings(Sentences and whole Documents)

This vector is a dense representation of the sentence's meaning in a multi-dimensional space. Sentences with similar meanings will have embeddings that are closer to each other in this space. This is the core idea behind using sentence transformers for tasks like semantic search or similarity comparison.

In [21]:
from sentence_transformers import SentenceTransformer

# Load model
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

# Convert text to text embeddings
vector = model.encode("Best movie ever!")

c:\Users\ptpl-648\Documents\Large_Language_Models\venv\Lib\site-packages\huggingface_hub\file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [22]:
vector.shape

(768,)

In [23]:
vector[0]

-0.02022047

In [24]:
vector

array([-2.02204697e-02,  4.57697473e-02, -1.26636783e-02, -3.37979314e-03,
       -2.54914770e-03, -3.31096211e-03, -4.58366387e-02,  2.32390892e-02,
       -3.12584974e-02, -3.15589309e-02, -2.19783466e-02,  3.67823755e-03,
        3.39108612e-03, -1.88130289e-02, -2.65822262e-02, -1.45891886e-02,
        3.20067368e-02, -3.66492663e-03,  1.75410174e-02,  5.43209128e-02,
       -3.96661721e-02,  9.93629545e-03, -3.27204242e-02, -1.62909869e-02,
        6.36532344e-03, -1.24458773e-02,  1.04737123e-02,  3.08674388e-02,
        7.47453701e-03, -3.86319868e-02, -6.19924664e-02, -3.25308964e-02,
       -1.40267508e-02,  5.16587645e-02,  1.69651696e-06, -1.74289336e-04,
       -1.27885467e-03, -4.15052250e-02,  5.00353612e-03,  4.58600894e-02,
       -2.85336655e-02,  5.02370633e-02, -1.75184365e-02, -3.98976175e-04,
        1.63311567e-02,  5.89937754e-02, -2.21730154e-02, -4.00975309e-02,
       -6.60433946e-03, -2.97633167e-02, -3.18221413e-02, -1.77945327e-02,
       -1.54363755e-02, -

# Word Embedding beyond LLMs

In [25]:
import gensim.downloader as api

# Download embeddings (66MB, glove, trained on wikipedia, vector size: 50)
# Other options include "word2vec-google-news-300"
model = api.load("glove-wiki-gigaword-50")

The **Word2Vec** model is loaded to find words that are most similar in meaning to the word "king".

The output of this code will be a list of tuples, where each tuple contains a word and its **similarity score to "king"**. The words are ordered from most similar to least similar. This demonstrates how word embeddings can capture **semantic relationships** between words.

In [26]:
model.most_similar([model['king']], topn=11)

[('king', 1.0000001192092896),
 ('prince', 0.8236179351806641),
 ('queen', 0.7839043140411377),
 ('ii', 0.7746230363845825),
 ('emperor', 0.7736247777938843),
 ('son', 0.766719400882721),
 ('uncle', 0.7627150416374207),
 ('kingdom', 0.7542161345481873),
 ('throne', 0.7539914846420288),
 ('brother', 0.7492411136627197),
 ('ruler', 0.7434253692626953)]

# Recommending songs by Embeddings

This code snippet downloads two files containing playlist data and song metadata, then processes them to create a list of playlists and a pandas DataFrame of songs.

In [28]:
import pandas as pd
from urllib import request

# Get the playlist dataset file
data = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/train.txt')

# Parse the playlist dataset file. Skip the first two lines as
# they only contain metadata
lines = data.read().decode("utf-8").split('\n')[2:]

# Remove playlists with only one song
playlists = [s.rstrip().split() for s in lines if len(s.split()) > 1]

# Load song metadata
songs_file = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/song_hash.txt')
songs_file = songs_file.read().decode("utf-8").split('\n')
songs = [s.rstrip().split('\t') for s in songs_file]
songs_df = pd.DataFrame(data=songs, columns = ['id', 'title', 'artist'])
songs_df = songs_df.set_index('id')

In [29]:
data

In [30]:
lines[9]

'484 485 486 487 488 489 490 19 491 492 14 4 493 494 74 395 299 495 70 496 461 459 87 482 27 459 460 459 460 87 497 498 499 500 501 502 503 504 505 506 507 87 '

In [31]:
print( 'Playlist #1:\n ', playlists[0], '\n')
print( 'Playlist #2:\n ', playlists[1])

Playlist #1:
  ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '2', '42', '43', '44', '45', '46', '47', '48', '20', '49', '8', '50', '51', '52', '53', '54', '55', '56', '57', '25', '58', '59', '60', '61', '62', '3', '63', '64', '65', '66', '46', '47', '67', '2', '48', '68', '69', '70', '57', '50', '71', '72', '53', '73', '25', '74', '59', '20', '46', '75', '76', '77', '59', '20', '43'] 

Playlist #2:
  ['78', '79', '80', '3', '62', '81', '14', '82', '48', '83', '84', '17', '85', '86', '87', '88', '74', '89', '90', '91', '4', '73', '62', '92', '17', '53', '59', '93', '94', '51', '50', '27', '95', '48', '96', '97', '98', '99', '100', '57', '101', '102', '25', '103', '3', '104', '105', '106', '107', '47', '108', '109', '110', '111', '112', '113', '25', '63', '62', '114', '115', '84', '116', '117',

**model = Word2Vec(...)**: This line initializes and trains the Word2Vec model.
playlists: This is the input data for training. It's the list of playlists where each playlist is a list of song IDs. The Word2Vec model will learn relationships between songs based on their co-occurrence within these playlists.


*   **vector_size=32**: This parameter specifies the dimensionality of the word
vectors (embeddings). Each song ID will be represented by a 32-dimensional vector. A higher dimensionality can capture more complex relationships but requires more data and computational resources.
*   **window=20**: This is the maximum distance between the current song and the predicted song within a playlist. The model considers songs within this window when learning their relationships.
*   **negative=50**: This parameter specifies the number of "negative" samples to use for training. Negative sampling is a technique used to improve training efficiency by sampling a small number of irrelevant words (songs) to train the model to distinguish them from relevant ones.
*   **min_count=1**: This parameter sets the minimum frequency of a word (song ID) for it to be included in the model's vocabulary. min_count=1 means that even songs that appear only once in the entire dataset will have an embedding.
*   **workers=4**: This parameter specifies the number of worker threads to use for training. Using multiple workers can speed up the training process on multi-core processors.







In [32]:
from gensim.models import Word2Vec

# Train our Word2Vec model
model = Word2Vec(
    playlists, vector_size=32, window=20, negative=50, min_count=1, workers=4
)

In [33]:
song_id = 2172

# Ask the model for songs similar to song #2172
model.wv.most_similar(positive=str(song_id))

[('2640', 0.9968711733818054),
 ('3167', 0.9968188405036926),
 ('2849', 0.9965357184410095),
 ('6624', 0.9963452219963074),
 ('10084', 0.9962297081947327),
 ('3126', 0.9961662292480469),
 ('5634', 0.9955615997314453),
 ('6658', 0.9955447316169739),
 ('3094', 0.9954848289489746),
 ('6626', 0.9951786398887634)]

In [34]:
print(songs_df.iloc[2172])

title     Fade To Black
artist        Metallica
Name: 2172 , dtype: object


In [35]:
print(songs_df.iloc[6626])

title      Blackout
artist    Scorpions
Name: 6626 , dtype: object


In [36]:
import numpy as np

def print_recommendations(song_id):
    similar_songs = np.array(
        model.wv.most_similar(positive=str(song_id),topn=5)
    )[:,0]
    return  songs_df.iloc[similar_songs]

# Extract recommendations
print_recommendations(2172)

title       artist
id                                          
2640              Red Barchetta         Rush
3167                  Unchained    Van Halen
2849           Run To The Hills  Iron Maiden
6624    Everybody Wants Some!!!    Van Halen
10084         Detroit Rock City         Kiss

In [37]:
print(print_recommendations(6626))

                         title                               artist
id                                                                 
11517   Mary Had A Little Lamb  Stevie Ray Vaughan & Double Trouble
10105           Three Lock Box                          Sammy Hagar
6641        Shout At The Devil                          Motley Crue
1922                       One                            Metallica
2172             Fade To Black                            Metallica
